### ISSUE TITLE
PULL_REQUEST_TEMPLATE: Update with new task list items

### ISSUE THREAD

**Issue by johlju** [dsccommunity/FailoverClusterDsc#166]
I suggest we update the task list with a few items and clarify already existing. This list is updated to reflect review comments I often have to do (here and in SqlServerDsc), so I'm hoping this helps contributors from getting one less review comment from reviewers. 😄 
 
I suggest we update with this new task list in PULL_REQUEST_TEMPLATE.md. Not all of these should be checked for each PR, and it already says in a comment in the PULL_REQUEST_TEMPLATE.md; 'Change to [x] for each task in the task list that applies to this PR'.

- [ ] Added an entry under the Unreleased section in CHANGELOG.md?
- [ ] Resource documentation added/updated in README.md?
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based help?
- [ ] Comment-based help added/updated?
- [ ] Localization strings added/updated?
- [ ] Examples appropriately added/updated?
- [ ] Unit tests added/updated? See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where applicable)? See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to Style Guidelines? See [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

**Comment by johlju** [comment]
This has been fixed with updating to the latest pipeline files from the project Sampler.
